### ISSUE TITLE
Error in significant conditions in one factor with three levels

### ISSUE THREAD

**Issue by MilesBremridgeUOM** [ajstewartlang/15_mixed_models_pt1#2]
In the one factor with three levels section there is a slight error in reporting the significant conditions. In the video it is correct by saying the only significant condition is negative vs positive. However, on the actual page, it is reported that it is neutral vs. positive which is not correct and is the least significant condition.

**Comment by ajstewartlang** [comment]
Thanks for spotting that! It's a typo on the page - I've now corrected that.
